import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import styles from '../styles/Main.module.sass'
import Button from '../components/Button'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className={styles.heroWrapper}>
        <div className={styles.heroTitle}>
          <h1>
            Hi 👋 I'm Ivan, a product designer, artist, coder
          </h1>
          <p>
            I have a passion to design/developing leading digital products. The last 7 years spent collaborating with awesome professionals, developing top products that changed lives. I'm interested in complex design systems, web3, user/dev experience, math, 3D and engineering. Tech Nation Global Talent Visa.
          </p>
          <Button type='button'  children={'Schedule a call 🤙'}/>
        </div>
        <div className={styles.avatarWrapper}>
          <div className={styles.avatarImage}>
            <Image 
                  src="/images/avatar.png"
                  alt="Ivan Sipilov"
                  width={720}
                  height={720}
            />
            <div className={styles.sunIllustration}>
              <Image 
                    src="/images/sun.svg"
                    alt="Ivan Sipilov"
                    width={240}
                    height={240}
              />
            </div>
          </div>
        </div>
      </div>

        <div className={styles.backGridWrapper}>
          <div className={styles.backGrid}></div>
          <div className={styles.backGrid}></div>
          <div className={styles.backGrid}></div>
          <div className={styles.backGrid}></div>
          <div className={styles.backGrid}></div>
          <div className={styles.backGrid}></div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
